# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ofc < Formula
  desc "Open Floor Control - multi-agent conversation protocol"
  homepage "https://ofc.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.2.0/ofc_0.2.0_darwin_amd64.tar.gz"
      sha256 "cadf7395f6750d2712a135f06101f5deebf8529ffb0f883fa8540cb5919b7843"

      define_method(:install) do
        bin.install "ofc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.2.0/ofc_0.2.0_darwin_arm64.tar.gz"
      sha256 "4c06e111e5875514f52a7153ca7f90141b14d307a4d53449ebd6c76035852017"

      define_method(:install) do
        bin.install "ofc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.2.0/ofc_0.2.0_linux_amd64.tar.gz"
      sha256 "2b656899896ab83aea6559e7f0402ad5d39e37ddc0c5e0417cd9a4914d4bc2e7"
      define_method(:install) do
        bin.install "ofc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.2.0/ofc_0.2.0_linux_arm64.tar.gz"
      sha256 "f69a3193519880f41d78b5e1aeb2405c807462c3aa71233186b24d274b08bb9d"
      define_method(:install) do
        bin.install "ofc"
      end
    end
  end

  test do
    system "#{bin}/ofc", "--version"
  end
end
