# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ofc < Formula
  desc "Open Floor Control - multi-agent conversation protocol"
  homepage "https://ofc.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.1.0/ofc_0.1.0_darwin_amd64.tar.gz"
      sha256 "226992bddff639bdac543dc8a8fbe01527b105c722977eee8a0c31e7cca33a80"

      def install
        bin.install "ofc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.1.0/ofc_0.1.0_darwin_arm64.tar.gz"
      sha256 "6531914491211d594d264c86158f007c4770b54b1e7e3b42ddca320d61025c1a"

      def install
        bin.install "ofc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.1.0/ofc_0.1.0_linux_amd64.tar.gz"
      sha256 "419ec42bb9fcdc9c10e56fe428d720793a27b9ceab54ae00b599cdb81f8d2373"
      def install
        bin.install "ofc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openfloorcontrol/ofc/releases/download/v0.1.0/ofc_0.1.0_linux_arm64.tar.gz"
      sha256 "e4a9f2bec6d5ba048d3666a513c312c036cc2f741a2f79f960c9ff964738a769"
      def install
        bin.install "ofc"
      end
    end
  end

  test do
    system "#{bin}/ofc", "--version"
  end
end
